language: go

before_install:
    - make get

go:
    - 1.12.x

env:
    - GO111MODULE=on

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-movienight .
      - docker images
