language: go

before_install:
    - make get

go:
    - 1.12.x

env:
    - GO111MODULE=on

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - export TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
    - docker build -t $DOCKER_USERNAME/movienight:$TRAVIS_TAG .
    - docker images
    - docker push $DOCKER_USERNAME/movienight:$TRAVIS_TAG
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        docker tag $DOCKER_USERNAME/movienight:$TRAVIS_TAG $DOCKER_USERNAME/movienight:latest
        docker push $DOCKER_USERNAME/movienight:latest
      fi
