language: go

before_install:
    - make get

go:
    - 1.12.x

env:
    - GO111MODULE=on

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/movienight:$TRAVIS_COMMIT .
    - docker images
